print("            (\____/)")    
print("            / @__@ \\")
print("           (  (oo)  )")
print("            `-.~~.-'")
print("             /    \ ")
print("           @/      \_")
print("          (/ /    \ \)")
